name: Daily Green Contribution Graph

on:
  schedule:
    # Runs every day at 00:00 UTC (5:30 AM IST)
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual run from GitHub Actions UI

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make Daily Commit
        run: |
          git config --global user.name "Pruthviraj Ganihar"
          git config --global user.email "ganiharpruthviraj@gmail.com"
          git commit --allow-empty -m "chore: daily activity log [skip ci]"
          git push origin main
